{
 "title": "llil.gq",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Go version",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "go_info", "legendFormat": "go_version" }
   ]
  },
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "HTTP Code: {{ code }}" }
   ]
  },
  {
   "title": "Handler root requests duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{handler=\"/\"}[5m])) by (le))",
     "legendFormat": "99th %ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler=\"/\"}[5m])) by (le))",
     "legendFormat": "95th %ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{handler=\"/\"}[5m])) by (le))",
     "legendFormat": "90th %ile"
    }
   ]
  },
  {
   "title": "Handler data shorten requests duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{handler=\"/data/shorten\"}[5m])) by (le))",
     "legendFormat": "99th %ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler=\"/data/shorten\"}[5m])) by (le))",
     "legendFormat": "95th %ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{handler=\"/data/shorten\"}[5m])) by (le))",
     "legendFormat": "90th %ile"
    }
   ]
  }
 ]
}