/*
 * URL Shortener API
 *
 * This is an URL Shortener API
 *
 * API version: 1.0.0
 * Contact: aurelien@duboc.xyz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"github.com/go-pg/pg/v10"
	"net/http"
	"strings"
)

type ReturnLongURL struct {
	db      *pg.DB
	baseUrl string
}

func (h *ReturnLongURL) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	if r.Method != "GET" {
		w.WriteHeader(http.StatusMethodNotAllowed)
		return
	}
	shortURL := strings.TrimPrefix(r.URL.Path, "/")
	fmt.Println(shortURL)
	shortUrlMap := new(ShortUrlMap)
	err := h.db.Model(shortUrlMap).Where("short_url = ?", shortURL).Select()
	fmt.Println(err)
	fmt.Println(shortUrlMap)
	if err != nil {
		w.WriteHeader(http.StatusNotFound)
		return
	}
	w.Header().Set("Location", shortUrlMap.LongURL)
	w.WriteHeader(301)
}
