/*
 * URL Shortener API
 *
 * This is a URL Shortener API
 *
 * API version: 1.0.0
 * Contact: aurelien@duboc.xyz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"github.com/go-pg/pg/v10"
	"net/http"
	"strings"
)

type ReturnLongURL struct {
	db *pg.DB
}

func (h *ReturnLongURL) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Access-Control-Allow-Origin", "*")
	w.Header().Set("Access-Control-Allow-Methods", "GET,OPTIONS")
	w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Access-Control-Allow-Headers")
	if r.Method == "OPTIONS" {
		w.WriteHeader(http.StatusNoContent)
		return
	}
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	if r.Method != "GET" {
		w.WriteHeader(http.StatusMethodNotAllowed)
		return
	}
	shortURL := strings.TrimPrefix(r.URL.Path, "/")
	shortUrlExist, shortUrlMap := selectShortURL(h.db, shortURL)
	if !shortUrlExist {
		w.Header().Set("Location", "/404")
		w.WriteHeader(302)
		return
	}
	w.Header().Set("Location", shortUrlMap.LongURL)
	w.WriteHeader(301)
}
