/*
 * URL Shortener API
 *
 * This is an URL Shortener API
 *
 * API version: 1.0.0
 * Contact: aurelien@duboc.xyz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/zteeed/llil.gq/1.0.0/",
		Index,
	},

	Route{
		"CreateNewShortURL",
		strings.ToUpper("Post"),
		"/zteeed/llil.gq/1.0.0/api/v1/data/shorten",
		CreateNewShortURL,
	},

	Route{
		"ReturnLongURL",
		strings.ToUpper("Get"),
		"/zteeed/llil.gq/1.0.0/api/v1/{shortUrl}",
		ReturnLongURL,
	},
}
